DROP DATABASE IF EXISTS lapoupee;

CREATE DATABASE IF NOT EXISTS lapoupee;
USE lapoupee;

DROP TABLE IF EXISTS GOODS;
DROP TABLE IF EXISTS CUSTOMER_INFO;
DROP TABLE IF EXISTS ORDER_INFO;
DROP TABLE IF EXISTS CART;


CREATE TABLE IF NOT EXISTS GOODS(
GOODS_ID INT(10) AUTO_INCREMENT,
GOODS_NAME VARCHAR(100) UNIQUE NOT NULL,
STOCK INT(4),
UNIT_PRICE INT(10),
PRIMARY KEY(GOODS_ID)
);


CREATE TABLE IF NOT EXISTS CUSTOMER_INFO(
CUSTOMER_ID INT(10)  AUTO_INCREMENT,
CUSTOMER_NAME VARCHAR(50) NOT NULL,
CUSTOMER_PASS VARCHAR(25) NOT NULL,
MAILADDRESS  VARCHAR(50) UNIQUE NOT NULL,
POSTCODE  VARCHAR(7) NOT NULL,
ADDRESS  VARCHAR(100) NOT NULL,
TELLNUMBER VARCHAR(12) NOT NULL,
HOUSENUMBER VARCHAR(100),
REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY(CUSTOMER_ID)
);



CREATE TABLE IF NOT EXISTS ORDER_INFO(
CUSTOMER_ID INT(10) NOT NULL,
GOODS_ID INT(10) NOT NULL,
ORDER_QUANTITY INT(3) NOT NULL,
TOTAL_AMOUNT BIGINT(10) NOT NULL,
PAY_MATHOD INT(1) NOT NULL,
CREDIT_COMPANY INT(1),
CREDIT_NUMBER BIGINT(16),
CON_SET INT(1),
BANK_SET INT(1),
PURCHASEDAY TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_INFO(CUSTOMER_ID),
FOREIGN KEY(GOODS_ID) REFERENCES GOODS(GOODS_ID)
);

CREATE TABLE IF NOT EXISTS CART(
TEMPORARY_ID VARCHAR(50) NOT NULL,
GOODS_NAME VARCHAR(100) NOT NULL,
SALES_COUNT INT(10) NOT NULL,
UNIT_PRICE INT(10) NOT NULL,
TOTAL_AMOUNT INT(10) NOT NULL
);

ALTER TABLE CART MODIFY COLUMN TOTAL_AMOUNT BIGINT NOT NULL;

INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("勇者",50,6000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("戦士",80,2000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("女戦士",80,3000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("騎士",60,2000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("魔法使い",60,3000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("魔女",30,7000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("僧侶",30,4000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("魔王",30,8000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("ドラゴン",60,6000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("ヴァンパイア",20,4000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("スライム",60,1000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("村人A",30,1000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("村人B",50,5000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("クボタ",60,5000);
INSERT INTO GOODS(GOODS_NAME,STOCK,UNIT_PRICE)VALUES("コボリ",40,50000);

INSERT INTO CUSTOMER_INFO(CUSTOMER_NAME,CUSTOMER_PASS,MAILADDRESS,POSTCODE,ADDRESS,TELLNUMBER,HOUSENUMBER
)VALUES(
"ikeda","ikeda123","ikeda@ikeda.co.jp","1234567","東京都八王子市xxx","09012345678","1-1-1");
INSERT INTO CUSTOMER_INFO(CUSTOMER_NAME,CUSTOMER_PASS,MAILADDRESS,POSTCODE,ADDRESS,TELLNUMBER,HOUSENUMBER
)VALUES(
"kuriya","kuriya","kuriya@kuriya.co.jp","1234567","東京都xxx","09012345678","1-1-1");
INSERT INTO CUSTOMER_INFO(CUSTOMER_NAME,CUSTOMER_PASS,MAILADDRESS,POSTCODE,ADDRESS,TELLNUMBER,HOUSENUMBER
)VALUES(
"hosoya","hosoya","hosoya@hosoya.co.jp","1234567","東京都xxx","09012345678","1-1-1");
INSERT INTO CUSTOMER_INFO(CUSTOMER_NAME,CUSTOMER_PASS,MAILADDRESS,POSTCODE,ADDRESS,TELLNUMBER,HOUSENUMBER
)VALUES(
"wada","wada","wada@wada.co.jp","1234567","東京都xxx","09012345678","1-1-1");
INSERT INTO CUSTOMER_INFO(CUSTOMER_NAME,CUSTOMER_PASS,MAILADDRESS,POSTCODE,ADDRESS,TELLNUMBER,HOUSENUMBER
)VALUES(
"mito","mito","mito@mito.co.jp","1234567","東京都八王子市xxx","09012345678","1-1-1");
